### ISSUE TITLE
Add dynamic link generation based on chapter

### ISSUE THREAD

**Issue by Redev22** [OverPoweredDev/Junior#25]
If i put in the "link" field the link of the novel i then always need to open it and search for the correct chapter between (sometimes) literally thousands of others.
Luckily a lot of novel websites use a simple NameOfTheWebsite.com/name-of-the-novel-ChapterNumber
Example: https://boxnovel.com/novel/the-tutorial-is-too-hard/chapter-307/

My request is to add a feature that dynamically generated the correct link with the right chapter:
Example input by the user (when creating the novel) https://boxnovel.com/novel/the-tutorial-is-too-hard/chapter-FUZZ/
The app logic searches for the word FUZZ (make it whatever you want) in the string and replaces it with the chapter number, this final link is the one that will be opened when you touch the "Link to novel" button in the homepage
There should also be a switch for this functionality when creating a novel because some sites don't follow this pattern for their URLs or require a few options to work correctly
Example https://dreamsofjianghu.ca/2018/10/18/adnd-001/ needs 0-padding on the left to make the number always 3 digits (here adnd is the short name of the novel)
Another example: this website appeared to have a linear progression that started from an high number but it's not always the same:
Chapter 11= https://m.wuxiaworld.co/Cultivation-Chat-Group/1253538.html
Chapter 12= https://m.wuxiaworld.co/Cultivation-Chat-Group/1253539.html (just +1)
Chapter 13= https://m.wuxiaworld.co/Cultivation-Chat-Group/1046598.html (wtf)
Chapter 14= https://m.wuxiaworld.co/Cultivation-Chat-Group/1253540.html (and we are back to normal)
So instead of adding support for all of these it's better to simply disable the function when needed.

**Comment by OverPoweredDev** [comment]
I'm a bit focused on getting `1.3.1` up with the reload on swiping up feature and updated bug report links. This one should be out by `1.3.2`

Only other thing I'm concerned about is that people might be confused on how to use it. Even the switch to Volume mode from chapter is hard to recognise. So any ideas for that, apart from the changelog of course?

**Comment by OverPoweredDev** [comment]
The `i` button gives me an idea, an extra menu just for a single option is kinda overkill. Plus it looks kinda ugly (That's why the Chapter/Volume and Ongoing/To Read/Complete stuff looks like it does now). Instead of making it a menu option, we can just keep it enabled all the time and only add the info button to the right of the Novel Link subtitle.

This works because something like `<num>` is very unlikely to show up in a url and constantly bombarding people with the descriptions for use would be super annoying. So adding a simple information pop-up on pressing the `i` would be more than enough to show people how it'll work.

Since I'm done with 1.3.1, I prototyped it to check how it looks and it seems great! Take a look

![Link Info](https://user-images.githubusercontent.com/64774148/137441664-d80dc41c-b6bc-4d86-96c4-255c9eb5c9d2.png)   ![Pop-Up](https://user-images.githubusercontent.com/64774148/137441660-07f33783-2c19-4ac3-8877-6c4410dc9efe.png)
